---
kind: pipeline
type: exec
name: blog

platform:
  os: linux
  arch: amd64

steps:
- name: remove_container
  failure: ignore
  commands:
  - docker container rm -f flask_proxy
- name: start_container
  commands:
  - docker run -d --name flask_proxy mystchen/flask_proxy:latest sh /run.sh